name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  remark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: npm install
      - run: npm run remark

  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby ## latest MRI
          bundler-cache: true
      - name: Run RuboCop
        run: bundle exec rubocop

  rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.0', '3.1', '3.2', '3.3' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Suppress git warnings
        run: git config --global init.defaultBranch main
      - name: Run RSpec
        run: bundle exec rspec
